"""Stable programmatic API for deterministic Wiki workflows.

Use this module, or the narrower ``wiki.*`` modules, for Python imports.
``med_ops.py`` is only the public terminal entrypoint.
"""
from __future__ import annotations

from wiki.agents import plan_subagents
from wiki.artifacts import (
    ARTIFACT_HTML_MANIFEST_SCHEMA,
    ARTIFACT_HTML_VALIDATION_SCHEMA,
    chat_id_from_raw,
    discover_artifact_manifests,
    required_artifacts_for_raw,
    validate_artifact_batch,
    validate_note_artifacts,
)
from wiki.common import (
    EXIT_IO,
    EXIT_LINKER,
    EXIT_MISSING,
    EXIT_OK,
    EXIT_USAGE,
    EXIT_VALIDATION,
    MIGRATION_PLAN_SCHEMA,
    MIGRATION_RECEIPT_SCHEMA,
    SUBAGENT_PLAN_SCHEMA,
    BLOCKER_RESOLUTION_SCHEMA,
    WIKI_HEALTH_FIX_SCHEMA,
    CollisionError,
    FileWriteError,
    MedOpsError,
    MissingPathError,
    ValidationError,
    _json,
    _now_iso,
)
from wiki.config import (
    DEFAULT_CATALOG_PATH,
    DEFAULT_LINKER_PATH,
    DEFAULT_RAW_DIR,
    DEFAULT_WIKI_DIR,
    MedConfig,
    _path,
    resolve_config,
    validate_config,
)
from wiki.coverage import (
    RAW_COVERAGE_SCHEMA,
    validate_raw_coverage,
    validate_raw_coverage_structure,
)
from wiki.graph_fixes import GRAPH_FIX_SCHEMA, fix_wiki_graph
from wiki.health import fix_wiki_health
from wiki.hygiene import (
    WIKI_HYGIENE_CLEANUP_SCHEMA,
    WIKI_HYGIENE_SCHEMA,
    cleanup_wiki_hygiene,
    collect_wiki_hygiene,
)
from wiki.linking import graph_audit, run_linker
from wiki.note_plan import (
    TRIAGE_NOTE_PLAN_SCHEMA,
    load_triage_note_plan,
    parse_triage_note_plan,
    serialize_triage_note_plan,
)
from wiki.publish import (
    plan_publish_batch,
    publish_batch,
    resolve_collision,
    stage_note,
    write_new_note,
)
from wiki.publish_receipts import (
    PUBLISH_DRY_RUN_RECEIPTS_SCHEMA,
    clear_publish_dry_run,
    publish_receipts_path,
    record_publish_dry_run,
    require_publish_dry_run,
)
from wiki.raw_chats import (
    BACKUP_CLEANUP_SCHEMA,
    atomic_write_text,
    create_backup,
    list_by_status,
    list_raw_files,
    mutate_raw_frontmatter,
    parse_frontmatter,
    prune_backup_files,
    raw_summary,
    read_note_meta,
    split_frontmatter,
    update_frontmatter,
)
from wiki.style import (
    apply_style_rewrite,
    fix_note_style_file,
    fix_wiki_style,
    validate_note_style_file,
    validate_wiki_note_contract,
    validate_wiki_style,
)
from wiki.taxonomy import (
    CANONICAL_AREA_ALIASES,
    CANONICAL_TAXONOMY,
    CANONICAL_TAXONOMY_ALIASES,
    TaxonomyResolution,
    _write_json_atomic,
    apply_taxonomy_migration,
    canonical_taxonomy_tree,
    normalize_taxonomy,
    resolve_target_for_note,
    resolve_taxonomy,
    rollback_taxonomy_migration,
    safe_title,
    target_for_note,
    taxonomy_audit,
    taxonomy_migration_plan,
    taxonomy_tree,
)

__all__ = [
    "CANONICAL_TAXONOMY",
    "CANONICAL_AREA_ALIASES",
    "CANONICAL_TAXONOMY_ALIASES",
    "DEFAULT_CATALOG_PATH",
    "DEFAULT_LINKER_PATH",
    "DEFAULT_RAW_DIR",
    "DEFAULT_WIKI_DIR",
    "EXIT_IO",
    "EXIT_LINKER",
    "EXIT_MISSING",
    "EXIT_OK",
    "EXIT_USAGE",
    "EXIT_VALIDATION",
    "MIGRATION_PLAN_SCHEMA",
    "MIGRATION_RECEIPT_SCHEMA",
    "PUBLISH_DRY_RUN_RECEIPTS_SCHEMA",
    "RAW_COVERAGE_SCHEMA",
    "ARTIFACT_HTML_MANIFEST_SCHEMA",
    "ARTIFACT_HTML_VALIDATION_SCHEMA",
    "TRIAGE_NOTE_PLAN_SCHEMA",
    "SUBAGENT_PLAN_SCHEMA",
    "BLOCKER_RESOLUTION_SCHEMA",
    "WIKI_HEALTH_FIX_SCHEMA",
    "WIKI_HYGIENE_CLEANUP_SCHEMA",
    "WIKI_HYGIENE_SCHEMA",
    "GRAPH_FIX_SCHEMA",
    "BACKUP_CLEANUP_SCHEMA",
    "CollisionError",
    "FileWriteError",
    "MedConfig",
    "MedOpsError",
    "MissingPathError",
    "TaxonomyResolution",
    "ValidationError",
    "_json",
    "_now_iso",
    "_path",
    "_write_json_atomic",
    "apply_style_rewrite",
    "apply_taxonomy_migration",
    "atomic_write_text",
    "canonical_taxonomy_tree",
    "chat_id_from_raw",
    "clear_publish_dry_run",
    "cleanup_wiki_hygiene",
    "collect_wiki_hygiene",
    "create_backup",
    "discover_artifact_manifests",
    "fix_note_style_file",
    "fix_wiki_health",
    "fix_wiki_graph",
    "fix_wiki_style",
    "graph_audit",
    "list_by_status",
    "list_raw_files",
    "load_triage_note_plan",
    "mutate_raw_frontmatter",
    "normalize_taxonomy",
    "parse_frontmatter",
    "parse_triage_note_plan",
    "plan_publish_batch",
    "plan_subagents",
    "publish_batch",
    "publish_receipts_path",
    "prune_backup_files",
    "raw_summary",
    "read_note_meta",
    "record_publish_dry_run",
    "required_artifacts_for_raw",
    "resolve_collision",
    "resolve_config",
    "resolve_target_for_note",
    "resolve_taxonomy",
    "require_publish_dry_run",
    "rollback_taxonomy_migration",
    "run_linker",
    "safe_title",
    "serialize_triage_note_plan",
    "split_frontmatter",
    "stage_note",
    "target_for_note",
    "taxonomy_audit",
    "taxonomy_migration_plan",
    "taxonomy_tree",
    "update_frontmatter",
    "validate_config",
    "validate_artifact_batch",
    "validate_note_style_file",
    "validate_note_artifacts",
    "validate_raw_coverage",
    "validate_raw_coverage_structure",
    "validate_wiki_note_contract",
    "validate_wiki_style",
    "write_new_note",
]
